### ISSUE TITLE
RCE模块有一些问题

### ISSUE THREAD

**Issue by gbymat** [Limingxing00/Retinal-Vessel-Segmentation-ISBI2022#1]
复现过程中，在RCE模块里面遇到topk的部分会报错
Traceback (most recent call last):
  File "D:/Users/huTao/Desktop/Retinal-Vessel-Segmentation-ISBI2022-main/train.py", line 259, in <module>
    train(i)
  File "D:/Users/huTao/Desktop/Retinal-Vessel-Segmentation-ISBI2022-main/train.py", line 140, in train
    x1, x2 = model(data, ratio)
  File "D:\ProgramData\Anaconda3\envs\yolo5\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Users\huTao\Desktop\Retinal-Vessel-Segmentation-ISBI2022-main\network\twonet.py", line 179, in forward
    x2 = self.transform1(x1, x, ratio)
  File "D:\Users\huTao\Desktop\Retinal-Vessel-Segmentation-ISBI2022-main\network\twonet.py", line 160, in transform1
    img = self.resultsErasing(img, x, ratio)
  File "D:\Users\huTao\Desktop\Retinal-Vessel-Segmentation-ISBI2022-main\network\twonet.py", line 39, in __call__
    max_list = input[n, i_c, ...].flatten().topk(int(f_p*self.top_n))[0] # top max value
RuntimeError: invalid argument 5: k not in range for dimension at C:/w/b/windows/pytorch/aten/src\THC/generic/THCTensorTopK.cu:24

请问有没有什么解决方法

**Comment by Limingxing00** [comment]
您好，因为最近在忙毕业。我需要等到三月三十一号才能重新验证代码。但是您可以尝试将 `Retinal-Vessel-Segmentation-ISBI2022/lib/xxx.yaml`里面的`RCE_RATIO: a`改为`RCE_RATIO: a/100` 进行尝试嘛？

Hello, I'm busy graduating recently. I need to wait until March 31st to re-verify the code. But can you try changing `RCE_RATIO: a` in `Retinal-Vessel-Segmentation-ISBI2022/lib/xxx.yaml` to `RCE_RATIO: a/100`?

**Comment by Limingxing00** [comment]
The issue has been unresponsive for a long time, so it is closed.
