### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Moonlongnight** [Limingxing00/Retinal-Vessel-Segmentation-ISBI2022#3]
你好，有一些问题需要咨询一下
1. 请问出现了梯度无法回传的问题，是如何解决的，根据本人的调试，需要将RCE擦除策略中设置x2并且令 x2=x.clone()，最后返回x2可以解决。
2.为什么模型训练2次？在train.py的main函数中model.train,同时在train函数中也有model.train
3.为什么训练时候一直不收敛，loss收敛到0.5左右不再变化
希望能得到回复，谢谢！同时希望能继续交流一下，我的email是：cmx976037282@mail.ustc.edu.cn

**Comment by Miranda-h** [comment]
@cmx157841 你好，请问你解决这个问题了吗？我也遇到了相同的问题，如果可以的话想一起交流一下，谢谢

**Comment by lyb765420** [comment]
@Moonlongnight 你好，梯度无法回传是怎么解决的
`Traceback (most recent call last):
  File "/home/liuyb/code/sdxx/复现/Retinal Vessel Segmentation with Pixel-wise Adaptive Filters/Retinal-Vessel-Segmentation-ISBI2022-main/train.py", line 274, in <module>
    train(i)
  File "/home/liuyb/code/sdxx/复现/Retinal Vessel Segmentation with Pixel-wise Adaptive Filters/Retinal-Vessel-Segmentation-ISBI2022-main/train.py", line 162, in train
    loss.backward()  #! retain_graph=True
    ^^^^^^^^^^^^^^^
  File "/home/liuyb/anaconda3/envs/sdxx/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/liuyb/anaconda3/envs/sdxx/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [5, 3, 175, 169]] is at version 30; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

**Comment by ZejunHe** [comment]
> @Moonlongnight 你好，梯度无法回传是怎么解决的 `Traceback (most recent call last): File "/home/liuyb/code/sdxx/复现/Retinal Vessel Segmentation with Pixel-wise Adaptive Filters/Retinal-Vessel-Segmentation-ISBI2022-main/train.py", line 274, in <module> train(i) File "/home/liuyb/code/sdxx/复现/Retinal Vessel Segmentation with Pixel-wise Adaptive Filters/Retinal-Vessel-Segmentation-ISBI2022-main/train.py", line 162, in train loss.backward() #! retain_graph=True ^^^^^^^^^^^^^^^ File "/home/liuyb/anaconda3/envs/sdxx/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward torch.autograd.backward( File "/home/liuyb/anaconda3/envs/sdxx/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [5, 3, 175, 169]] is at version 30; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

你好，问题解决了吗

**Comment by shanbiu** [comment]
I have same problem.

> @Moonlongnight 你好，梯度无法回传是怎么解决的 `Traceback (most recent call last): File "/home/liuyb/code/sdxx/复现/Retinal Vessel Segmentation with Pixel-wise Adaptive Filters/Retinal-Vessel-Segmentation-ISBI2022-main/train.py", line 274, in <module> train(i) File "/home/liuyb/code/sdxx/复现/Retinal Vessel Segmentation with Pixel-wise Adaptive Filters/Retinal-Vessel-Segmentation-ISBI2022-main/train.py", line 162, in train loss.backward() #! retain_graph=True ^^^^^^^^^^^^^^^ File "/home/liuyb/anaconda3/envs/sdxx/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward torch.autograd.backward( File "/home/liuyb/anaconda3/envs/sdxx/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [5, 3, 175, 169]] is at version 30; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`
